# This file was generated automatically by export.py

from typing import Sequence
from typing import Callable
from typing import BinaryIO
from typing import overload
from typing import NamedTuple
from typing import TextIO
from typing import Tuple
from typing import Optional
from typing import IO
from typing_extensions import Literal
from typing import Iterator
MODE = Literal['r', 'rb', 'w', 'wb']
class Stat(NamedTuple):
  size: int
  mtime: float
def copy(src: str, dst: str, overwrite: bool=..., return_md5: bool=...) -> Optional[str]:
  ...
def exists(path: str) -> bool:
  ...
def glob(pattern: str) -> Iterator[str]:
  ...
def isdir(path: str) -> bool:
  ...
def listdir(path: str) -> Iterator[str]:
  ...
def makedirs(path: str) -> None:
  ...
def remove(path: str) -> None:
  ...
def rmdir(path: str) -> None:
  ...
def stat(path: str) -> Stat:
  ...
def walk(top: str, topdown: bool=..., onerror: Optional[Callable]=...) -> Iterator[Tuple[str, Sequence[str], Sequence[str]]]:
  ...
def basename(path: str) -> str:
  ...
def dirname(path: str) -> str:
  ...
def join(a: str) -> str:
  ...
def get_url(path: str) -> Tuple[str, Optional[float]]:
  ...
def md5(path: str) -> str:
  ...
def set_log_callback(fn: Callable[[str], None]) -> None:
  ...
@overload
def BlobFile(path: str, mode: Literal['rb'], buffer_size: int=...) -> BinaryIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['wb'], buffer_size: int=...) -> BinaryIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['r'], buffer_size: int=...) -> TextIO:
  ...
@overload
def BlobFile(path: str, mode: Literal['w'], buffer_size: int=...) -> TextIO:
  ...
def BlobFile(path: str, mode: MODE=..., buffer_size: int=...) -> IO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['rb'], cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['wb'], cache_dir: Optional[str]=...) -> BinaryIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['r'], cache_dir: Optional[str]=...) -> TextIO:
  ...
@overload
def LocalBlobFile(path: str, mode: Literal['w'], cache_dir: Optional[str]=...) -> TextIO:
  ...
def LocalBlobFile(path: str, mode: MODE=..., cache_dir: Optional[str]=...) -> IO:
  ...
